### ISSUE TITLE
Can you document the oidc response field used to match the user ?

### ISSUE THREAD

**Issue by menardorama** [Timshel/vaultwarden#47]
Hi,

Thanks a lot for creating such fork and maintaining it since last september !

I have a question regarding the field used to match the user in vaultwarden.
If I am not wrong vaultwarden seems to use email address as unique identifier; linking the already existing account using SSO is working great.

But what happen when a user change it's email adress on the SSO side ? (Like change the format, or getting married...).

Is the sso part is using the preferred_username or the email address ?

Should be great to be abble to configure the unique identier :)

Thanks anyway

**Comment by Timshel** [comment]
Hey

It relies on an identifier made of the `IdToken` claims: `{iss}/{sub}`. So it's possible to change the email later on (but it needs to be done manually by the user in Vaultwarden since the email is referenced in the key; a notification email is sent if the provider email does not match the Vaultwarden email anymore).

Wrote a bit on the subject here: [SSO.md#account-and-email-handling](https://github.com/Timshel/vaultwarden/blob/sso-support/SSO.md#account-and-email-handling)  :)

**Comment by menardorama** [comment]
May I suggest that the merge field be configurable ?

For instance our unique identifier in my company is the username, maybe in other use case it's the email address.

I know that keycloak generate uuid at user creation but if a user is deleted and sync again from a ldap a new uuid is generated (shit happens...), we will need to modify the sso mapping table.

It would be a nice to have ☺️
Thanks

**Comment by Timshel** [comment]
The username has no unique constraint in Bitwarden and Vaultwarden, so it would need to change first.
You could ask the Vaultwarden maintainers if they are open to the idea but I doubt they will be.

But even with that it would only partially help in your example. Since the association work only if there is no sso user linked. In your case you would still need to remove the db association to allow the new user to link to the account.

**Comment by Timshel** [comment]
Will close for now, if you have other questions don't hesitate to open another issue :).
