### ISSUE TITLE
New docker image coming soon?

### ISSUE THREAD

**Issue by Daniel-dev22** [Timshel/vaultwarden#70]
Will there be an updated docker image at some point with latest commits from upstream that support the new mobile app.

**Comment by Timshel** [comment]
Hey,

Rebased and pushed a `testing` version, did some testing on it and it appears ok.
Waiting for a `vaultwarden` release for the next tagged version.

**Comment by Timshel** [comment]
`1.31.0-1` released.

**Comment by Timshel** [comment]
Hey
I'll start by being a bit preachy sorry 😅 , but outside a testing setup I would recommend using neither, since with both you are open to unwanted upgrade and rollback might become trickier if you have no log of the past deployed version (will depend on your setup).
I would recommend to always use a fixed version and check the [changelog](https://github.com/Timshel/vaultwarden/blob/main/CHANGELOG.md) in case there is some breaking change which could prevent rollback.

Back to your question, for `timshel/vaultwarden` release are in step with Vaultwarden, this make tracking which change are included easier and simplify work on my side, but it does mean that when there is no new Vaultwarden release for some time  minor fix might not be available in a named version (for an important issue I would backport it).

If you are comfortable running more unproven code one solution could be to look at the digest of the `testing` release and use it (I don't believe docker-hub prune the old layer when a new `testing` is pushed but I might be wrong).

Alternatively If you are ok with an unbranded version of Vaultwarden then [OIDCWarden image](https://hub.docker.com/r/timshel/oidcwarden/tags) are released with more frequency (but those are less tested). Should be a drop-in replacement but always make backup 😄.
